---
- name: "Run tasks install.yml"
  ansible.builtin.include_tasks: install.yml
  tags: always

- name: "Run tasks adblocker.yml"
  ansible.builtin.include_tasks: adblocker.yml
  tags: always

- name: "Run tasks blackhole.yml"
  ansible.builtin.include_tasks: blackhole.yml
  tags: always

- name: "Run tasks exporter.yaml"
  ansible.builtin.include_tasks: "exporter.yaml"
  tags: always
