---
# renovate: datasource=github-releases depName=k0sproject/k0s
k0s_version: v1.34.2+k0s.0

k0s_cluster_name: ""
k0s_labels: []

k0s_kubelet_args:
  - --max-pods=150

k0s_oidc_client_id: ""
k0s_oidc_client_secret: ""
k0s_oidc_issuer_url: ""
k0s_oidc_groups_claim: ""
k0s_oidc_groups_prefix: ""
k0s_oidc_username_prefix: ""

k0s_oidc_admin_group: ""

k0s_config_file: "/etc/k0s.yaml"

k0s_service_name: "k0s"
k0s_service_enabled: true

k0s_controllers_remove_noschedule: true

k0s_gitops_repo: "https://github.com/soerenschneider/k8s-gitops.git"
